first_name = "John"
last_name = "Doe"
age = "23"
height = "5'1"
is_active = True
full_name = first_name + " " + last_name

print("Full Name:", type (full_name))
print("First Name:", type(first_name))
print("Last Name:", type(last_name))
print("Age:", type(age))
print("Height:", type(height))
print("Is Active:", type(is_active))
print("Full Name:", full_name)
print("First Name:", first_name)
print("Last Name:", last_name)
print("Age:", age)
print("Height:", height)
print("Is Active:", is_active)
print("Data Types:")
print("First Name:", type(first_name))
print("Last Name:", type(last_name))
print("Age:", type(age))
print("Height:", type(height))
print("Is Active:", type(is_active))
print ("Full Name:", type(full_name))
print("Full Name:", full_name)
print("First Name:", first_name)
print("Last Name:", last_name)
print("Age:", age)
print("Height:", height)    
print("Is Active:", is_active)
print("Data Types:")
print("First Name:", type(first_name))
print("Last Name:", type(last_name))
print("Age:", type(age))
print("Height:", type(height))
print("Is Active:", type(is_active))
print ("Full Name:", type(full_name))
print("Full Name:", full_name)
print("First Name:", first_name)
print("Last Name:", last_name)
print("Age:", age)
print("Height:", height)
print("Is Active:", is_active)
print("Data Types:")
print("First Name:", type(first_name))
print("Last Name:", type(last_name))
print("Age:", type(age))
print("Height:", type(height))
print("Is Active:", type(is_active))
print ("Full Name:", type(full_name))
print("Full Name:", full_name)
print("First Name:", first_name)
print("Last Name:", last_name)
print("Age:", age)
print("Height:", height)
print("Is Active:", is_active)
print("Data Types:")
print("First Name:", type(first_name))
print("Last Name:", type(last_name))
print("Age:", type(age))
print("Height:", type(height))