first_name  = input("Enter your first name: ")
last_name   = input("Enter your last name: ")
print (f"Welcome {first_name} {last_name}!")
# The above code takes the user's first and last name as input and prints a welcome message.
# The input() function is used to take input from the user.
# The f-string is used to format the string and insert the values of first_name and last_name into the string.

print("Data Types:")
print("First Name:", type(first_name)) 
print("Last Name:", type(last_name))
print("Full Name:", type(first_name + " " + last_name))
print("First Name:", first_name)
print("Last Name:", last_name)
print("Full Name:", first_name + " " + last_name)
print("First Name Length:", len(first_name))
print("Last Name Length:", len(last_name))
print("Full Name Length:", len(first_name + last_name))
print("Full Name Uppercase:", first_name.upper() + " " + last_name.upper())
print("Full Name Lowercase:", first_name.lower() + " " + last_name.lower())
print("Full Name Titlecase:", first_name.title() + " " + last_name.title())
print("Full Name Capitalized:", first_name.capitalize() + " " + last_name.capitalize())
print("First Name is Alphabetic:", first_name.isalpha())
print("Last Name is Alphabetic:", last_name.isalpha())
print("First Name is Alphanumeric:", first_name.isalnum())
print("Last Name is Alphanumeric:", last_name.isalnum())
print("First Name is Lowercase:", first_name.islower())
print("Last Name is Lowercase:", last_name.islower())
print("First Name is Uppercase:", first_name.isupper())
print("Last Name is Uppercase:", last_name.isupper())
print("First Name is Titlecase:", first_name.istitle())
print("Last Name is Titlecase:", last_name.istitle())
print("First Name is Printable:", first_name.isprintable())
print("Last Name is Printable:", last_name.isprintable())
print("First Name is Space:", first_name.isspace())
print("Last Name is Space:", last_name.isspace())
print("First Name is Decimal:", first_name.isdecimal())
print("Last Name is Decimal:", last_name.isdecimal())
print("First Name is Numeric:", first_name.isnumeric())
print("Last Name is Numeric:", last_name.isnumeric())
print("First Name is Identifier:", first_name.isidentifier())
print("Last Name is Identifier:", last_name.isidentifier())
print("First Name is Digit:", first_name.isdigit())
print("Last Name is Digit:", last_name.isdigit())
print("First Name is Casefolded:", first_name.casefold())
print("Last Name is Casefolded:", last_name.casefold())
print("First Name is Centered:", first_name.center(10))
print("Last Name is Centered:", last_name.center(10))
print("First Name is Encoded:", first_name.encode())
print("Last Name is Encoded:", last_name.encode())
print("First Name is Expanded:", first_name.expandtabs())
print("Last Name is Expanded:", last_name.expandtabs())
print("First Name is Formatted:", first_name.format())
print("Last Name is Formatted:", last_name.format())
print("First Name is Justified:", first_name.ljust(10))
print("Last Name is Justified:", last_name.ljust(10))
print("First Name is Right Justified:", first_name.rjust(10))
print("Last Name is Right Justified:", last_name.rjust(10))
print("First Name is Stripped:", first_name.strip())
print("Last Name is Stripped:", last_name.strip())
print("First Name is Swapped:", first_name.swapcase())
print("Last Name is Swapped:", last_name.swapcase())
print("First Name is Zfilled:", first_name.zfill(10))
print("Last Name is Zfilled:", last_name.zfill(10))
print("First Name is Partitioned:", first_name.partition('a'))
print("Last Name is Partitioned:", last_name.partition('a'))
print("First Name is Split:", first_name.split())
print("Last Name is Split:", last_name.split())
print("First Name is Splitlines:", first_name.splitlines())
print("Last Name is Splitlines:", last_name.splitlines())
print("First Name is Startswith:", first_name.startswith('a'))
print("Last Name is Startswith:", last_name.startswith('a'))
print("First Name is Endswith:", first_name.endswith('a'))
print("Last Name is Endswith:", last_name.endswith('a'))  
# The above code takes the user's first and last name as input and prints a welcome message.
# The above code prints the data types of the variables first_name, last_name, and full name.

